name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Start server
      run: npm run server &
    - name: Start app
      run: npm run start
    - name: Execute tests
      run: npm run test
