name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install

    - name: Start server
      run: npm run server &
    # Waits before continuing to the next step.
    # Will try fixing it later. #
    ##- name: Wait for server to be ready
      ##run: npx wait-on http://localhost:3030
  
    - name: Start app
      run: npm run start &
    # Waits before continuing to the next step.
    # Will try fixing it later. #
   ## - name: Wait for app to be ready
     ## run: npx wait-on http://localhost:3000
      
    - name: Execute tests
      run: npm run test
